export {
    initialState,
    reduceState,
    Tick,
    Spawn,
    Flip,
    Restart,
    KillMario,
    Pause,
};

import {
    State,
    Action,
    TargetRect,
    Constants,
    Target,
    Mario,
    Viewport,
} from "./types";

import { RNG, rangeScale } from "./util";

const initialState: State = {
    gameEnd: false,
    gamePause: false,
    targetRects: [],
    velocity: Constants.VELOCITY,

    tickCount: 0,
    marioActivatedTick: 0,
    spawnCount: 0,

    marioSeed: Constants.SEED_MARIO,
    penaltySeed: Constants.SEED_PENALTY,
    marioMissStreak: 0,
    playerInput: [0, 0, 0, 0, 0, 0, 0, 0],
    score: 0,

    marioActive: false,
    marioClicked: false,
    marioPos: { x: 0, y: 0 },
};

const findLowestTarget = (
    targets: ReadonlyArray<TargetRect>,
): TargetRect | undefined =>
    targets.reduce<TargetRect | undefined>(
        (lowest, rect) =>
            lowest === undefined || rect.y > lowest.y ? rect : lowest,
        undefined,
    );

const checkReachLine = (targets: ReadonlyArray<TargetRect>): boolean => {
    const lowest = findLowestTarget(targets);
    return (
        lowest !== undefined &&
        lowest.y + Target.HEIGHT >= Viewport.CANVAS_HEIGHT
    );
};

function checkInput(
    playerInput: ReadonlyArray<number>,
    lowest: TargetRect | undefined,
): boolean {
    if (lowest === undefined) return false;
    const playerInputVal = playerInput.reduce((acc, bit) => acc * 2 + bit, 0);

    return playerInputVal === lowest.value;
}

const updateTgtPos = (
    targets: ReadonlyArray<TargetRect>,
): ReadonlyArray<TargetRect> =>
    targets.map(rect => ({ ...rect, y: rect.y + rect.velocity }));

const genMarioX = (seed: number): number =>
    Math.floor(
        rangeScale(RNG.scale(seed), 0, Viewport.CANVAS_WIDTH - Mario.WIDTH),
    );

const genMarioY = (seed: number): number =>
    Math.floor(
        rangeScale(
            RNG.scale(seed),
            0,
            Viewport.CANVAS_HEIGHT - Constants.DIGIT_HEIGHT - Mario.HEIGHT,
        ),
    );

const genPenaltyIndex = (seed: number, count: number): number =>
    Math.floor(rangeScale(RNG.scale(seed), 0, count - 1));

const applyMarioPenalty = (
    targets: ReadonlyArray<TargetRect>,
    seed: number,
    missStreak: number,
): ReadonlyArray<TargetRect> => {
    if (targets.length === 0) return targets;

    const accRectIndex = genPenaltyIndex(seed, targets.length);
    const boost = missStreak * Constants.ACCELERATION;

    return targets.map((rect, index) =>
        index === accRectIndex
            ? { ...rect, velocity: rect.velocity + boost }
            : rect,
    );
};

const applyMatch = (s: State): State => {
    const movedRects = updateTgtPos(s.targetRects),
        lowestTarget = findLowestTarget(movedRects),
        matched = checkInput(s.playerInput, lowestTarget);

    return {
        ...s,
        targetRects: matched
            ? movedRects.filter(rect => rect !== lowestTarget)
            : movedRects,
        score: matched ? s.score + 1 : s.score,
        playerInput: matched ? Constants.EMPTY_PLAYER_INPUT : s.playerInput,
    };
};

const applyMarioLifeCyc = (s: State): State => {
    const newTickCount = s.tickCount + 1,
        expired =
            s.marioActive &&
            newTickCount - s.marioActivatedTick >= Constants.MARIO_EXPIRE,
        stillActive = s.marioActive && !expired,
        missedUnclicked = expired && !s.marioClicked,
        newMissStreak = missedUnclicked
            ? s.marioMissStreak + 1
            : s.marioMissStreak,
        newPenaltySeed = missedUnclicked
            ? RNG.hash(s.penaltySeed)
            : s.penaltySeed;

    return {
        ...s,
        targetRects: missedUnclicked
            ? applyMarioPenalty(s.targetRects, newPenaltySeed, newMissStreak)
            : s.targetRects,
        tickCount: newTickCount,
        marioActive: stillActive,
        marioMissStreak: newMissStreak,
        penaltySeed: newPenaltySeed,
    };
};

const pipe =
    (...fns: ReadonlyArray<(s: State) => State>) =>
    (s: State): State =>
        fns.reduce((acc, f) => f(acc), s);

const guardBy =
    (blocked: (s: State) => boolean) =>
    (f: (s: State) => State) =>
    (s: State): State =>
        blocked(s) ? s : f(s);

const whilePlaying = guardBy(s => s.gameEnd || s.gamePause);

class Tick implements Action {
    apply = whilePlaying(
        pipe(applyMatch, applyMarioLifeCyc, s =>
            checkReachLine(s.targetRects) ? { ...s, gameEnd: true } : s,
        ),
    );
}

class Spawn implements Action {
    constructor(private readonly value: number) {} // pre-generated by the spawn$ stream

    apply(s: State): State {
        const newSpawnCount = s.spawnCount + 1,
            checkAccRes = newSpawnCount % Constants.ACC_COUNT === 0,
            checkMarioSpawnRes =
                newSpawnCount % Constants.MARIO_SPAWN_COUNT === 0,
            newMarioSeed = RNG.hash(s.marioSeed),
            marioSeedX = RNG.hash(newMarioSeed),
            marioSeedY = RNG.hash(marioSeedX),
            newVelocity = checkAccRes
                ? s.velocity + Constants.ACCELERATION
                : s.velocity,
            newTarget: TargetRect = {
                y: Constants.SPAWN_Y,
                value: this.value,
                velocity: newVelocity,
            };

        return {
            ...s,
            targetRects: [...s.targetRects, newTarget],
            velocity: newVelocity,
            spawnCount: newSpawnCount,
            marioSeed: newMarioSeed,
            marioActivatedTick: checkMarioSpawnRes
                ? s.tickCount
                : s.marioActivatedTick,
            marioActive: checkMarioSpawnRes || s.marioActive,
            marioClicked: checkMarioSpawnRes ? false : s.marioClicked,
            marioPos: checkMarioSpawnRes
                ? {
                      x: genMarioX(marioSeedX),
                      y: genMarioY(marioSeedY),
                  }
                : s.marioPos,
        };
    }
}

class KillMario implements Action {
    apply = guardBy(
        s =>
            s.gameEnd ||
            s.gamePause ||
            !s.marioActive ||
            s.marioClicked ||
            s.targetRects.length === 0,
    )(s => ({
        ...s,
        targetRects: s.targetRects.slice(1),
        marioClicked: true,
        marioMissStreak: 0,
    }));
}

class Flip implements Action {
    constructor(private readonly index: number) {} // starts from 0

    apply(s: State): State {
        return whilePlaying(state => ({
            ...state,
            playerInput: state.playerInput.map((bit, index) =>
                index === this.index ? 1 - bit : bit,
            ),
        }))(s);
    }
}

class Restart implements Action {
    apply(_: State): State {
        return initialState;
    }
}

class Pause implements Action {
    apply = guardBy(s => s.gameEnd)(s => ({ ...s, gamePause: !s.gamePause }));
}

const reduceState = (s: State, action: Action): State => action.apply(s);

/**
 * 23: 00100011 (3, 7, 8)
 * DB: 11011011 (1, 2, 4, 5, 7, 8)
 * 2:  00000010 (7)
 * B5: 10110101 (1, 3, 4, 6, 8)
 * 99: 10011001 (1, 4, 5, 8)
 * 78: 01111000 (2, 3, 4, 5)
 * 44: 01000100 (2, 6)
 * */
